# Generated by Django 5.2.5 on 2025-09-11 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_item_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='location',
            field=models.CharField(choices=[('fci', 'FCI - Faculty of Computing and Informatics'), ('fom', 'FOM - Faculty of Management'), ('foe', 'FOE - Faculty of Engineering'), ('fcm', 'FCM - Faculty of Creative Multimedia'), ('stc', 'STC - Student Service Centre')], default=0.0006584362139917695, max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='pickup_location_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
