# Generated by Django 5.2.5 on 2025-09-12 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_remove_item_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='location',
            field=models.CharField(choices=[('fci', 'FCI'), ('fcm', 'FCM'), ('fom', 'FOM'), ('foe', 'FOE'), ('stc', 'STC'), ('lp', 'LP'), ('hb1', 'HB1'), ('hb2', 'HB2'), ('hb3', 'HB3'), ('hb4', 'HB4')], default='fci', max_length=50),
        ),
    ]
