# Generated by Django 5.2.5 on 2025-09-12 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_item_location_item_pickup_location_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='location',
        ),
        migrations.RemoveField(
            model_name='item',
            name='pickup_location_name',
        ),
    ]
